name = "szz"
license = "MIT"
licenselink = "https://github.com/sunzhe96/szz/blob/main/LICENSE"
description = "A minimal hugo theme for personal blog"
homepage = "https://github.com/sunzhe96/szz"
min_version = "0.41.0"

[author]
  name = "Zhe Sun"
  homepage = "https://sunzhe.info"
